//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaplinkAPI.SOAP
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteAddress", Namespace="http://schemas.datacontract.org/2004/07/MaplinkAPI.SOAP")]
    public partial class RouteAddress : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private string CityField;
        
        private string NumberField;
        
        private string StateField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteType", Namespace="http://schemas.datacontract.org/2004/07/MaplinkAPI.SOAP")]
    public enum RouteType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StandardRoute = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AvoidTrafic = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteResult", Namespace="http://schemas.datacontract.org/2004/07/MaplinkAPI.SOAP")]
    public partial class RouteResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DistanceField;
        
        private string ErrorMsgField;
        
        private string FuelCostField;
        
        private string FuelCostWithTaxField;
        
        private string TimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distance
        {
            get
            {
                return this.DistanceField;
            }
            set
            {
                this.DistanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg
        {
            get
            {
                return this.ErrorMsgField;
            }
            set
            {
                this.ErrorMsgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuelCost
        {
            get
            {
                return this.FuelCostField;
            }
            set
            {
                this.FuelCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuelCostWithTax
        {
            get
            {
                return this.FuelCostWithTaxField;
            }
            set
            {
                this.FuelCostWithTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time
        {
            get
            {
                return this.TimeField;
            }
            set
            {
                this.TimeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRouteCalculatorService")]
public interface IRouteCalculatorService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteCalculatorService/GetRoute", ReplyAction="http://tempuri.org/IRouteCalculatorService/GetRouteResponse")]
    MaplinkAPI.SOAP.RouteResult GetRoute(MaplinkAPI.SOAP.RouteAddress[] address, MaplinkAPI.SOAP.RouteType route);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRouteCalculatorService/GetRoute", ReplyAction="http://tempuri.org/IRouteCalculatorService/GetRouteResponse")]
    System.Threading.Tasks.Task<MaplinkAPI.SOAP.RouteResult> GetRouteAsync(MaplinkAPI.SOAP.RouteAddress[] address, MaplinkAPI.SOAP.RouteType route);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRouteCalculatorServiceChannel : IRouteCalculatorService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RouteCalculatorServiceClient : System.ServiceModel.ClientBase<IRouteCalculatorService>, IRouteCalculatorService
{
    
    public RouteCalculatorServiceClient()
    {
    }
    
    public RouteCalculatorServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RouteCalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RouteCalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RouteCalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public MaplinkAPI.SOAP.RouteResult GetRoute(MaplinkAPI.SOAP.RouteAddress[] address, MaplinkAPI.SOAP.RouteType route)
    {
        return base.Channel.GetRoute(address, route);
    }
    
    public System.Threading.Tasks.Task<MaplinkAPI.SOAP.RouteResult> GetRouteAsync(MaplinkAPI.SOAP.RouteAddress[] address, MaplinkAPI.SOAP.RouteType route)
    {
        return base.Channel.GetRouteAsync(address, route);
    }
}
